### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by axic** [comment]
@fulldecent thanks! For good measure I've just merged a license file, if you agree with Apache-2.0 I'll merge this PR.

**Comment by fulldecent** [comment]
👍 Agree to Apache license for contributions

**Comment by fulldecent** [comment]
Bump -- good to merge

**Comment by fulldecent** [comment]
Good to merge

**Comment by fulldecent** [comment]
Ping.

**Comment by fulldecent** [comment]
ping @axic

**Comment by fulldecent** [comment]
@axic Ready to merge

**Pull request closed without merging**
